2022-04-17 21:51:18.619 | DEBUG    | aria2p.interface:run:504 - Created new screen <tests.test_interface.MockedScreen object at 0x7f87740d0ed0>
2022-04-17 21:51:18.620 | DEBUG    | aria2p.interface:run:519 - Got event None
2022-04-17 21:51:18.620 | DEBUG    | aria2p.interface:run:535 - Tick! Updating data and rows
2022-04-17 21:51:18.633 | DEBUG    | aria2p.interface:run:542 - Refresh! Printing text
2022-04-17 21:51:18.639 | DEBUG    | aria2p.interface:run:519 - Got event MouseEvent (1000, 0) 1
2022-04-17 21:51:18.639 | ERROR    | aria2p.interface:run:529 - clicked outside of boundaries
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
    │                │      └ 'gw3-worker'
    │                └ <execnet.gateway_base.Popen2IO object at 0x7f8777f9a910>
    └ <class 'execnet.gateway_base.WorkerGateway'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
    │    │         └ <function WorkerPool.integrate_as_primary_thread at 0x7f87780d3ce0>
    │    └ <execnet.gateway_base.WorkerPool object at 0x7f8777fb95d0>
    └ <execnet.gateway_base.WorkerGateway object at 0x7f8777fb9310>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
    │    │              └ <execnet.gateway_base.Reply object at 0x7f8777fb9d90>
    │    └ <function WorkerPool._perform_spawn at 0x7f87780d3ec0>
    └ <execnet.gateway_base.WorkerPool object at 0x7f8777fb95d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
    │     └ <function Reply.run at 0x7f87780d3ba0>
    └ <execnet.gateway_base.Reply object at 0x7f8777fb9d90>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
    │              │     │       └ {}
    │              │     └ ((<Channel id=1 open>, ('"""\n    This module is executed in remote subprocesses and helps to\n    control a remote testing s...
    │              └ <bound method WorkerGateway.executetask of <execnet.gateway_base.WorkerGateway object at 0x7f8777fb9310>>
    └ <execnet.gateway_base.Reply object at 0x7f8777fb9d90>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
    │       │   └ {'channel': <Channel id=1 open>, '__name__': '__channelexec__', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in...
    │       └ <code object <module> at 0x7f8777fbd290, file "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 1>
    └ <built-in function exec>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 291, in <module>
    config.hook.pytest_cmdline_main(config=config)
    │      │    │                          └ <_pytest.config.Config object at 0x7f87769b69d0>
    │      │    └ <_HookCaller 'pytest_cmdline_main'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f87769a2f50>
    └ <_pytest.config.Config object at 0x7f87769b69d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'config': <_pytest.config.Config object at 0x7f87769b69d0>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8776f4cb80>
           │    │         │    │     └ <_HookCaller 'pytest_cmdline_main'>
           │    │         │    └ 'pytest_cmdline_main'
           │    │         └ <_HookCaller 'pytest_cmdline_main'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>>
           └ <_HookCaller 'pytest_cmdline_main'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'config': <_pytest.config.Config object at 0x7f87769b69d0>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_cmdline_main'
           │    └ <function _multicall at 0x7f8776f07ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<_pytest.config.Config object at 0x7f87769b69d0>]
          │         └ <function pytest_cmdline_main at 0x7f8776c05940>
          └ <HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
           │            │       └ <function _main at 0x7f8776c059e0>
           │            └ <_pytest.config.Config object at 0x7f87769b69d0>
           └ <function wrap_session at 0x7f8776c058a0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
    │       │            │    │       └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
    │       │            │    └ <_pytest.config.Config object at 0x7f87769b69d0>
    │       │            └ <function _main at 0x7f8776c059e0>
    │       └ <ExitCode.OK: 0>
    └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
    │      │    │                          └ <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>
    │      │    └ <_HookCaller 'pytest_runtestloop'>
    │      └ <pluggy._hooks._HookRelay object at 0x7f87769a2f50>
    └ <_pytest.config.Config object at 0x7f87769b69d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8776f4cb80>
           │    │         │    │     └ <_HookCaller 'pytest_runtestloop'>
           │    │         │    └ 'pytest_runtestloop'
           │    │         └ <_HookCaller 'pytest_runtestloop'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>>
           └ <_HookCaller 'pytest_runtestloop'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'session': <Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>}
           │    │               │          └ [<HookImpl plugin_name='main', plugin=<module '_pytest.main' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/mai...
           │    │               └ 'pytest_runtestloop'
           │    └ <function _multicall at 0x7f8776f07ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Session tests exitstatus=<ExitCode.OK: 0> testsfailed=1 testscollected=480>]
          │         └ <bound method WorkerInteractor.pytest_runtestloop of <__channelexec__.WorkerInteractor object at 0x7f87758af1d0>>
          └ <HookImpl plugin_name='140219769352656', plugin=<__channelexec__.WorkerInteractor object at 0x7f87758af1d0>>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 91, in pytest_runtestloop
    self.run_one_test(torun)
    │    │            └ [276, 277, 278, 279]
    │    └ <function WorkerInteractor.run_one_test at 0x7f877699ff60>
    └ <__channelexec__.WorkerInteractor object at 0x7f87758af1d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/xdist/remote.py", line 110, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
    │    │      │    │                            │              └ <Function test_sort_edges>
    │    │      │    │                            └ <Function test_click_out_bounds>
    │    │      │    └ <_HookCaller 'pytest_runtest_protocol'>
    │    │      └ <pluggy._hooks._HookRelay object at 0x7f87769a2f50>
    │    └ <_pytest.config.Config object at 0x7f87769b69d0>
    └ <__channelexec__.WorkerInteractor object at 0x7f87758af1d0>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'item': <Function test_click_out_bounds>, 'nextitem': <Function test_sort_edges>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8776f4cb80>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_protocol'>
           │    │         │    └ 'pytest_runtest_protocol'
           │    │         └ <_HookCaller 'pytest_runtest_protocol'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>>
           └ <_HookCaller 'pytest_runtest_protocol'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'item': <Function test_click_out_bounds>, 'nextitem': <Function test_sort_edges>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_protocol'
           │    └ <function _multicall at 0x7f8776f07ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_click_out_bounds>, <Function test_sort_edges>]
          │         └ <function pytest_runtest_protocol at 0x7f877643cf40>
          └ <HookImpl plugin_name='rerunfailures', plugin=<module 'pytest_rerunfailures' from '/media/data/dev/aria2p/__pypackages__/3.11...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pytest_rerunfailures.py", line 240, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
              │               │              └ <Function test_sort_edges>
              │               └ <Function test_click_out_bounds>
              └ <function runtestprotocol at 0x7f8776be7f60>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
    │       │      │               │             └ False
    │       │      │               └ <Function test_click_out_bounds>
    │       │      └ <function call_and_report at 0x7f8776c04360>
    │       └ <method 'append' of 'list' objects>
    └ [<TestReport 'test_interface.py::test_click_out_bounds' when='setup' outcome='passed'>]
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
           │                 │     │       └ {}
           │                 │     └ 'call'
           │                 └ <Function test_click_out_bounds>
           └ <function call_runtest_hook at 0x7f8776c04540>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
           │        └ <classmethod(<function CallInfo.from_call at 0x7f8776c04b80>)>
           └ <class '_pytest.runner.CallInfo'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
            │        │          └ <function call_runtest_hook.<locals>.<lambda> at 0x7f87741962a0>
            │        └ +TResult
            └ typing.Optional
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
            │          │       └ {}
            │          └ <Function test_click_out_bounds>
            └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ False
           │    │         │    │     │    │                └ {'item': <Function test_click_out_bounds>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8776f4cb80>
           │    │         │    │     └ <_HookCaller 'pytest_runtest_call'>
           │    │         │    └ 'pytest_runtest_call'
           │    │         └ <_HookCaller 'pytest_runtest_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>>
           └ <_HookCaller 'pytest_runtest_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ False
           │    │               │          │        └ {'item': <Function test_click_out_bounds>}
           │    │               │          └ [<HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_runtest_call'
           │    └ <function _multicall at 0x7f8776f07ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_click_out_bounds>]
          │         └ <function pytest_runtest_call at 0x7f8776c04180>
          └ <HookImpl plugin_name='runner', plugin=<module '_pytest.runner' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
    │    └ <function Function.runtest at 0x7f8776c57560>
    └ <Function test_click_out_bounds>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
    │    │                                   └ <Function test_click_out_bounds>
    │    └ <property object at 0x7f8776d3bb00>
    └ <Function test_click_out_bounds>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
           │    │         │    │     │    │                │       └ True
           │    │         │    │     │    │                └ {'pyfuncitem': <Function test_click_out_bounds>}
           │    │         │    │     │    └ <function _HookCaller.get_hookimpls at 0x7f8776f4cb80>
           │    │         │    │     └ <_HookCaller 'pytest_pyfunc_call'>
           │    │         │    └ 'pytest_pyfunc_call'
           │    │         └ <_HookCaller 'pytest_pyfunc_call'>
           │    └ <bound method PluginManager._hookexec of <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>>
           └ <_HookCaller 'pytest_pyfunc_call'>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           │    │               │          │        │       └ True
           │    │               │          │        └ {'pyfuncitem': <Function test_click_out_bounds>}
           │    │               │          └ [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest...
           │    │               └ 'pytest_pyfunc_call'
           │    └ <function _multicall at 0x7f8776f07ba0>
           └ <_pytest.config.PytestPluginManager object at 0x7f87769a2e50>
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
          │         │         └ [<Function test_click_out_bounds>]
          │         └ <function pytest_pyfunc_call at 0x7f8776c54360>
          └ <HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/...
  File "/media/data/dev/aria2p/__pypackages__/3.11/lib/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
             │              └ {'server': <tests.conftest._Aria2Server object at 0x7f87740d3f10>, 'monkeypatch': <_pytest.monkeypatch.MonkeyPatch object at ...
             └ <function test_click_out_bounds at 0x7f8774408900>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 412, in test_click_out_bounds
    run_interface(
    └ <function run_interface at 0x7f8774373560>

  File "/media/data/dev/aria2p/tests/test_interface.py", line 98, in run_interface
    interface.run()
    │         └ <function Interface.run at 0x7f8775472840>
    └ <aria2p.interface.Interface object at 0x7f87740d12d0>

> File "/media/data/dev/aria2p/src/aria2p/interface.py", line 523, in run
    self.process_event(event)
    │    │             └ MouseEvent (1000, 0) 1
    │    └ <function Interface.process_event at 0x7f8775472a20>
    └ <aria2p.interface.Interface object at 0x7f87740d12d0>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 590, in process_event
    self.process_mouse_event(event)
    │    │                   └ MouseEvent (1000, 0) 1
    │    └ <function Interface.process_mouse_event at 0x7f8775472f20>
    └ <aria2p.interface.Interface object at 0x7f87740d12d0>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 905, in process_mouse_event
    self.state_mapping[self.state]["process_mouse_event"](event)
    │    │             │    │                             └ MouseEvent (1000, 0) 1
    │    │             │    └ 0
    │    │             └ <aria2p.interface.Interface object at 0x7f87740d12d0>
    │    └ {0: {'process_keyboard_event': <bound method Interface.process_keyboard_event_main of <aria2p.interface.Interface object at 0...
    └ <aria2p.interface.Interface object at 0x7f87740d12d0>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 910, in process_mouse_event_main
    new_sort = self.get_column_at_x(event.x)
               │    │               │     └ 1000
               │    │               └ MouseEvent (1000, 0) 1
               │    └ <function Interface.get_column_at_x at 0x7f8775473b00>
               └ <aria2p.interface.Interface object at 0x7f87740d12d0>

  File "/media/data/dev/aria2p/src/aria2p/interface.py", line 1140, in get_column_at_x
    raise ValueError("clicked outside of boundaries")

ValueError: clicked outside of boundaries
2022-04-17 21:51:18.648 | DEBUG    | aria2p.interface:run:531 - Got event KeyboardEvent: 113
2022-04-17 21:51:18.648 | DEBUG    | aria2p.interface:run:525 - Received exit command
